return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "elixir",
        "eex",
        "haskell",
        "heex",
        "html",
        "javascript",
        "json",
        "just",
        "lua",
        "markdown",
        "markdown_inline",
        "php",
        "python",
        "typescript",
        "sql",
        "vim",
        "vue",
        "yaml",
        "zig",
        "zsh",
      },
    },
  },
}
